export enum OrganizationParametersKey {
    CATEGORY_WORKITEM_TYPES = 'category_workitems_type',
    TIMEZONE_CONFIG = 'timezone_config',
    REVIEW_MODE_CONFIG = 'review_mode_config',
    KODY_FINE_TUNING_CONFIG = 'kody_fine_tuning_config',
    AUTO_JOIN_CONFIG = 'auto_join_config',
    BYOK_CONFIG = 'byok_config',
    COCKPIT_METRICS_VISIBILITY = 'cockpit_metrics_visibility',
    AUTO_LICENSE_ASSIGNMENT = 'auto_license_assignment',
    CODE_REVIEW_PRESET = 'code_review_preset',
    LICENSE_KEY = 'license_key',
    LICENSE_ASSIGNED_USERS = 'license_assigned_users',
    FIRST_REVIEW_AT = 'first_review_at',
    SPEND_LIMIT_CONFIG = 'spend_limit_config',
    GLOBAL_RULES_SOURCE_REPOSITORIES = 'global_rules_source_repositories',
}
