export enum JobStatus {
    PENDING = 'PENDING',
    PROCESSING = 'PROCESSING',
    COMPLETED = 'COMPLETED',
    FAILED = 'FAILED',
    WAITING_FOR_EVENT = 'WAITING_FOR_EVENT',
    CANCELLED = 'CANCELLED',
}
